apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-courseapi-image
  labels:
    app: my-courseapi-image
spec:

  selector:
    matchLabels:
      app: my-courseapi-image
  replicas: 2
  strategy:
    type: RollingUpdate


  template:
    metadata:
      labels:
        app: my-courseapi-image
    spec:
      containers:
      - name: my-courseapi-image
        image: my-courseapi-image
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 8888
