
apiVersion: v1
kind: Service
metadata:
  name: my-courseapi-service
spec:
  selector:
    app: my-courseapi-image
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888

# port - The port on which the service is fetched